name: WorldGuardGamemodeFixer
main: de.redstoneworld.worldguardgamemodefixer.WorldGuardGamemodeFixer
version: 1.1.1
api-version: 1.19
depend: [WorldGuard]
description: The Plugin description here.
authors: [RedstoneFuture]
website: https://redstoneworld.de